### PR TITLE
added --nagios option to produce Nagios output

### PR DESCRIPTION
**Pull request by AxelNennker**
Signed-off-by: Axel Nennker <axel.nennker@telekom.de>

when validator-info is called with option --nagios then now Nagios compatible output is generated

### CODE REVIEW

**Comment by hyperledger-github** [comment]
Could one of the committers please verify this patch?

**Comment by ashcherbakov** [comment]
(ci) test this please

**Comment by anikitinDSR** [comment]
Also, verbose output of validator-info was extended. 
Details in https://jira.hyperledger.org/browse/INDY-1175
For example you can run 'validator-info -v'

**Comment by AxelNennker** [comment]
the extended output is not part of this PR

**Pull request merged**
