### PR TITLE
[INDY-1861] integrate new request handlers

### PR DESCRIPTION
**Pull request by anikitinDSR**
Signed-off-by: Andrew Nikitin <andrew.nikitin@dsr-corporation.com>

### CODE REVIEW

**Comment by anikitinDSR** [comment]
test this please

**Comment by andkononykhin** [comment]
test this please

**Comment by andkononykhin** [comment]
test this please

**Comment by andkononykhin** [comment]
test this please

**Comment by ashcherbakov** [comment]
test this please

**Pull request merged**
