### PR TITLE
enableRichSchemas feature flag - take 1

### PR DESCRIPTION
**Pull request by AlexJonsson**
Aside from pulling the config variable 'enableRichSchemas' into the various CONTEXT related functions, I wasn't sure how else to implement this feature flag. Looking forward to improving this over time. I haven't been able to get my development workbench up for indy-node (only been just able to set up a von network). Will work to figure that out better. Have a great weekend!

### CODE REVIEW

**Comment by skhoroshavin** [comment]
(ci) test this please

**Comment by AlexJonsson** [comment]
Not sure but the DCO check seems to be repo owner related, right?

**Comment by WadeBarnes** [comment]
> Not sure but the DCO check seems to be repo owner related, right?

@AlexJonsson, All Hyperledger contributions require author signoff on all commits.  Details on how to amend your commit can be found here; https://github.com/hyperledger/indy-node/pull/1626/checks?check_run_id=1266975922

**Comment by AlexJonsson** [comment]
Hi All; the warnings thrown in the LGTM link presume that the indy_common.config.py module is not imported first before the other modules (transactions, constants). Unless someone can point out the order of import of these modules upon build, I would submit that these cyclic warnings are alright (or someone else please provide 2nd opinion). @esplinr

**Review by Toktar — COMMENTED** [review]
Thanks a lot for your PR! It is really very important for the system, but there are some comments. The codebase is complex and not transparent somewhere. For a merge this PR would be great to do follow items:
- remove direct feature flag imports and remove all feature flag checks (marked these places with comments)
- add flag check to static validation  https://github.com/hyperledger/indy-node/blob/e5f91ff51946202eaeccd7e18d3adaf266406f93/indy_node/server/request_handlers/domain_req_handlers/rich_schema/abstract_rich_schema_object_handler.py#L38  and read it through `indy_common.config_util getConfig()`. If rich schemas are disabled, respond to the client with NACK.
- add a test that by default rich schema transactions are not written to the ledger and the client receives NACK reply.
- in tests that fall to make the inclusion of this feature flag through the tconf fixture. An example of changing configs in tests: https://github.com/hyperledger/indy-node/blob/e2577df5eba3c17adc38a2b76f6a85f34b64ffeb/indy_node/test/upgrade/test_broken_connection_control_tool.py#L26
If you have any questions, feel free to ask. I'll be glad to help.

**Comment by AlexJonsson** [comment]
@Toktar the link for the request handler comes from the main branch; since it is on a different branch maybe it's better if someone on your team handles this merge? 
image

**Comment by AlexJonsson** [comment]
Closed after meeting with 11/24 Indy contributors call

**Pull request closed without merging**
