### PR TITLE
Fixed python to python3

### PR DESCRIPTION
**Pull request by cam-parra**
Due to the fact that if you are not running a Linux distro (aka mac) you will get an error.

### CODE REVIEW

**Comment by hyperledger-github** [comment]
Could one of the committers please verify this patch?

**Comment by ashcherbakov** [comment]
Please add a DCO signature

**Comment by ashcherbakov** [comment]
test this please

**Comment by ashcherbakov** [comment]
test this please

**Comment by esplinr** [comment]
DCO is still failing.

**Comment by ashcherbakov** [comment]
Please re-create the PR with a correct DCO

**Pull request closed without merging**
