### PR TITLE
Fix three typos

### PR DESCRIPTION
**Pull request by ken-ebert**
Signed-off-by: Kenneth Ebert <ken@kindredlearning.com>
Replaces #1343 (same content changes, but fixed my repository issues and DCO)

### CODE REVIEW

**Comment by hyperledger-github** [comment]
Could one of the committers please verify this patch?

**Comment by andkononykhin** [comment]
(CI) test this please

**Comment by ken-ebert** [comment]
This is a doc only change. It should have no implications to CI.

**Comment by andkononykhin** [comment]
@ken-ebert Sure. But CI's status is required for merge. Failed tests don't relate to the changes, it's a kind of intermittent issues that will be explored.

**Comment by andkononykhin** [comment]
test this please

**Comment by ken-ebert** [comment]
@andkononykhin Thanks for the clarification.

**Pull request merged**
