### PR TITLE
Update start-nodes.md with working sudo syntax

### PR DESCRIPTION
**Pull request by coderintherye**
This fixes a line that will error out with permission denied due to the appending / redirect of output not having sudo, instead running it as an encapsulated sudo command. Fixes INDY-1964 https://jira.hyperledger.org/browse/INDY-1964

### CODE REVIEW

**Comment by hyperledger-github** [comment]
Could one of the committers please verify this patch?

**Comment by ashcherbakov** [comment]
@coderintherye can you please fix the DCO?

**Comment by coderintherye** [comment]
@ashcherbakov Ok I think DCO has been resolved now

**Comment by ashcherbakov** [comment]
(ci) test this please

**Comment by ashcherbakov** [comment]
@coderintherye 
It looks like there is conflict (I think just because the doc files have been moved into a subfolder).
Can you please resolve it?

**Comment by coderintherye** [comment]
@ashcherbakov Ok, I merged in the upstream master and re-pushed and it's got the change in the right spot now, though I think the tests will have to run again

**Comment by ashcherbakov** [comment]
(ci) test this please

**Comment by coderintherye** [comment]
thanks @ashcherbakov , feels good to get something in, hopefully I will start contributing more substantive changes soon :)

**Pull request merged**
