### PR TITLE
Getting Started Guide is moved.

### PR DESCRIPTION
**Pull request by kukgini**
`Getting Started Guide` is move to `Indy Workthrough`.

### CODE REVIEW

**Comment by hyperledger-github** [comment]
Could one of the committers please verify this patch?

**Comment by ashcherbakov** [comment]
Please add a correct DCO

**Comment by kukgini** [comment]
I fixed the DCO following instruction. And It seems passed.

**Comment by ashcherbakov** [comment]
(ci) test this please

**Pull request merged**
