### PR TITLE
Fix: file path reference

### PR DESCRIPTION
**Pull request by pysingh**
setup_dev_python.sh which is incorrect reference.

### CODE REVIEW

**Comment by hyperledger-github** [comment]
Could one of the committers please verify this patch?

**Comment by ashcherbakov** [comment]
@pysingh  Can you please add DCO signature to your commit (-s argument)?

**Comment by pysingh** [comment]
@ashcherbakov I've added SCO, please review it.

**Comment by ashcherbakov** [comment]
test this please

**Comment by ashcherbakov** [comment]
DCO check doesn't work for some reasons... Looks like we have to re-create the PR

**Comment by pysingh** [comment]
Closing this, created a new one!

**Pull request closed without merging**
