### PR TITLE
fix: file reference

### PR DESCRIPTION
**Pull request by pysingh09**
Signed-off-by: Piyush <pysingh09@gmail.com>

### CODE REVIEW

**Comment by hyperledger-github** [comment]
Could one of the committers please verify this patch?

**Comment by hyperledger-github** [comment]
Could one of the committers please verify this patch?

**Comment by pysingh** [comment]
test this please

**Comment by andkononykhin** [comment]
test this please

**Comment by andkononykhin** [comment]
Duplicates merged #823

**Pull request closed without merging**
