### PR TITLE
typo

### PR DESCRIPTION
**Pull request by AxelNennker**

### CODE REVIEW

**Comment by hyperledger-github** [comment]
Could one of the committers please verify this patch?

**Comment by ashcherbakov** [comment]
Can you please add DCO signature to your commits?

**Comment by AxelNennker** [comment]
Signed-off-by: Axel Nennker <axel.nennker@telekom.de>

**Comment by ashcherbakov** [comment]
@AxelNennker  You have to modify your commit to add a signature there (https://github.com/probot/dco#how-it-works).

**Comment by AxelNennker** [comment]
added dco but that did not show up here. So new PR #630 and closing this one.

**Pull request closed without merging**
