### PR TITLE
INDY-1285: Update README typo

### PR DESCRIPTION
**Pull request by Steve-Boyd**
In "Prerequisites section, change "used" to "user"

### CODE REVIEW

**Comment by hyperledger-github** [comment]
Could one of the committers please verify this patch?

**Comment by ashcherbakov** [comment]
Please add DCO signature to the Commit as required by Hyperledger policy

**Comment by Steve-Boyd** [comment]
Sorry about that, updated.

**Comment by ashcherbakov** [comment]
test this please

**Comment by ashcherbakov** [comment]
test this please

**Comment by ashcherbakov** [comment]
test this please

**Comment by esplinr** [comment]
Jenkins is unblocked and is now testing. The pull request is expected to be merged soon.

**Comment by ashcherbakov** [comment]
test this please

**Pull request merged**
