### PR TITLE
INDY-1709: Faulty primary can make pool re-order requests

### PR DESCRIPTION
**Pull request by ArtObr**
Signed-off-by: ArtObr <artemobruchnikov@gmail.com>

### CODE REVIEW

**Comment by ArtObr** [comment]
Ticket for resolving this problem https://jira.hyperledger.org/browse/INDY-1709

**Comment by ArtObr** [comment]
Apparently, this issue has been fixed. Recheck this test. Close PR if issue has gone.

**Comment by brentzundel** [comment]
What should we do with this PR? It has been open for a year an a half and the problem it fixes may not still be a problem.
I think it may be best to close it.

**Comment by brentzundel** [comment]
test this please

**Comment by brentzundel** [comment]
If CI/CD fails, the next step is to analyze why the build pipeline fails and fix the PR so it passes, otherwise we should merge the PR.

**Comment by cjhowland** [comment]
@ArtObr Could you provide a brief update on this PR? With recent branch changes and the current development process on Indy Node/Plenum, we are wondering if these changes are still viable. If so, please close this PR and retarget it to `main`.

We will discuss and determine which PRs should be merged or closed at the next Indy Contributors Working Group meeting on May 9, 2023.

**Comment by WadeBarnes** [comment]
Closing due to the PR becoming stale.

**Pull request closed without merging**
