### PR TITLE
added option --nagios to produce Nagios output

### PR DESCRIPTION
**Pull request by AxelNennker**
Signed-off-by: Axel Nennker <axel.nennker@telekom.de>

The new option '--nagios' to validator-info produces output like:

> 0 tlabs_Total_Config_Transactions config_transactions=0 tlabs Total Config Transactions
> 0 tlabs_Total_Ledger_Transactions ledger_transactions=4 tlabs Total Ledger Transactions
> 0 tlabs_Total_Pool_Transactions pool_transactions=3 tlabs Total Pool Transactions
> 0 tlabs_Read_Transactions_per_second read_transactions_per_second=0.00 tlabs Read Transactions/Second
> 0 tlabs_Write_Transactions_per_second write_transactions_per_second=0.00 tlabs Write Transactions/Second
> 0 tlabs_Number_of_Validators number_of_validators=3 tlabs Number of Validators
> 0 tlabs_Reachable_Validators reachable_validators=3 tlabs Reachable Validators
> 0 tlabs_Unreachable_Validators unreachable_validators=0 tlabs Unreachable Validators

On your node 'tlabs' is replaced by the name of the validator.

This output is compatible to Nagios. T-Labs uses it to monitor its Indy nodes with check_mk

### CODE REVIEW

**Comment by hyperledger-github** [comment]
Could one of the committers please verify this patch?

**Comment by anikitinDSR** [comment]
Also, please add sign-off for "Update validator-info".

**Comment by AxelNennker** [comment]
The original PR was signed off. Do I really have to sign off the addition of a blank?

**Comment by AxelNennker** [comment]
@anikitinDSR Regarding the ways on how to amend older commits github tells me that those require a force push which should be avoided.
How can I signed off Update validator-info without causing harm?

Axel

ps: too bad there isn't a 'Sign off this commit' next to the "The sign-off is missing"

**Comment by AxelNennker** [comment]
Closing this and doing it from scratch again as I fail to sign-off one commit

**Pull request closed without merging**
