### PR TITLE
Added ursa to the core.ubuntu.dockerfile install

### LINKED ISSUE #1624: Unable to start indy test network
Followed the instructions provided in the README.md file to [start a test network](https://github.com/hyperledger/indy-node#how-to-install-a-test-network),

Following command failed to execute `./pool_start.sh 4 10.0.0.2,10.0.0.3,10.0.0.4,10.0.0.5 10 9701`, below is the console output,

```
Creating pool
4 10.0.0.2,10.0.0.3,10.0.0.4,10.0.0.5 10
Creating pool of 4 nodes with ips 10.0.0.2,10.0.0.3,10.0.0.4,10.0.0.5
Creating a new node Node1 0.0.0.0 9701 0.0.0.0 9702
Setting up docker with systemd
The systemd cgroup hierarchy is already mounted at /sys/fs/cgroup/systemd.
Your Docker host is now configured for running systemd containers!
Building indybase
Sending build context to Docker daemon   34.3kB
Step 1/1 : FROM solita/ubuntu-systemd:16.04
 ---> ebf71084f672
Successfully built ebf71084f672
Successfully tagged indybase:latest
Building indycore for user 1000
Sending build context to Docker daemon   34.3kB
Step 1/13 : FROM indybase
 ---> ebf71084f672
Step 2/13 : ARG uid=1000
 ---> Using cache
 ---> 5bb1984e1a34
Step 3/13 : RUN apt-get update -y && apt-get install -y         git     wget    python3.5       python3-pip     python-setuptools       python3-nacl    apt-transport-https     ca-certificates
 ---> Using cache
 ---> 5fd2a788e057
Step 4/13 : RUN pip3 install -U         'pip<10.0.0'    setuptools
 ---> Using cache
 ---> 9b350415b376
Step 5/13 : RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
 ---> Using cache
 ---> cf28ce36c515
Step 6/13 : RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BD33704C
 ---> Using cache
 ---> 245d6fad4bed
Step 7/13 : RUN echo "deb https://repo.sovrin.org/deb xenial master" >> /etc/apt/sources.list
 ---> Using cache
 ---> dd3840bbfdb3
Step 8/13 : RUN echo "deb https://repo.sovrin.org/sdk/deb xenial master" >> /etc/apt/sources.list
 ---> Using cache
 ---> 4e09de1da87e
Step 9/13 : RUN useradd -ms /bin/bash -l -u $uid indy
 ---> Using cache
 ---> ec5d8907883f
Step 10/13 : RUN apt-get update -y && apt-get install -y indy-node libindy
 ---> Running in 376e9ed88430
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [518 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [2331 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [1494 kB]
Get:8 https://repo.sovrin.org/deb xenial InRelease [28.4 kB]
Get:9 https://repo.sovrin.org/sdk/deb xenial InRelease [28.5 kB]
Get:10 https://repo.sovrin.org/deb xenial/master amd64 Packages [344 kB]
Get:11 https://repo.sovrin.org/sdk/deb xenial/master amd64 Packages [524 kB]
Fetched 5593 kB in 9s (614 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 indy-node : Depends: indy-plenum (= 1.13.0~dev1024) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update -y && apt-get install -y indy-node libindy' returned a non-zero code: 100
```

### PR DESCRIPTION
**Pull request by pSchlarb**
Testpool started with the pool_start.sh script after the changes
Fixes #1624

Signed-off-by: Philipp Schlarb <p.schlarb@esatus.com>

### CODE REVIEW

**Comment by WadeBarnes** [comment]
(ci) test this please

**Comment by WadeBarnes** [comment]
I get the following errors when trying to build with this dockerfile:
```
#12 3.258 Some packages could not be installed. This may mean that you have
#12 3.258 requested an impossible situation or if you are using the unstable
#12 3.258 distribution that some required packages have not yet been created
#12 3.258 or been moved out of Incoming.
#12 3.258 The following information may help to resolve the situation:
#12 3.258
#12 3.258 The following packages have unmet dependencies:
#12 3.289  indy-node : Depends: indy-plenum (= 1.13.0.dev1034) but it is not going to be installed
#12 3.289              Depends: timeout-decorator (= 0.4.0) but it is not installable
#12 3.289              Depends: distro (= 1.3.0) but it is not installable
#12 3.295 E: Unable to correct problems, you have held broken packages.
#12 ERROR: executor failed running [/bin/sh -c apt-get update -y && apt-get install -y indy-node libindy ursa=0.3.2-2]: exit code: 100
```

**Comment by WadeBarnes** [comment]
The underlying issue in my case is this that the version of `indy-node` being installed is requiring `indy-plenum==1.13.0.dev1034` then is should be requiring `indy-plenum==1.13.0~dev1034`.  All versions of `indy-node` from version `1.13.0~dev1240` seem to be affected by this issue.

**Comment by WadeBarnes** [comment]
The issue was introduced here; https://github.com/hyperledger/indy-node/commit/5bf71f427925037acb11d6b7e171905174de300f

and then fixed here; https://github.com/hyperledger/indy-node/commit/6bd7f20deb79df6a1f4bc8906bba7bee6bf9f1a8

There is no package associated to the fix because the Jenkins builds have been failing to publish since October 14th.

I'd recommend switching over to the builds published via the GHA workflows.

```
# Hyperledger Repo Key
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9692C00E657DDE61

echo "deb  https://hyperledger.jfrog.io/artifactory/indy xenial main"  >> /etc/apt/sources.list
```

**Comment by WadeBarnes** [comment]
The Jenkins CD builds have been partially stuck due to `pip` version dependencies which should be resolved with https://github.com/hyperledger/indy-node/pull/1684.

**Comment by shashank-shekher** [comment]
The problem still persists to date. I got the following error while trying to build node with docker:

```
Step 8/13 : RUN echo "deb https://repo.sovrin.org/sdk/deb xenial master" >> /etc/apt/sources.list
 ---> Using cache
 ---> f70d55e90373
Step 9/13 : RUN useradd -ms /bin/bash -l -u $uid indy
 ---> Using cache
 ---> caa6b4b9e80f
Step 10/13 : RUN apt-get update -y && apt-get install -y indy-node libindy
 ---> Running in 5f344966b42c
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [99.8 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [99.8 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [97.4 kB]
Get:5 https://repo.sovrin.org/deb xenial InRelease [28.4 kB]
Get:6 https://repo.sovrin.org/sdk/deb xenial InRelease [30.9 kB]
Get:7 https://repo.sovrin.org/deb xenial/master amd64 Packages [351 kB]
Get:8 https://repo.sovrin.org/sdk/deb xenial/master amd64 Packages [558 kB]
Fetched 1265 kB in 3s (378 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 indy-node : Depends: indy-plenum (= 1.13.0.dev1034) but it is not going to be installed
             Depends: timeout-decorator (= 0.4.0) but it is not installable
             Depends: distro (= 1.3.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update -y && apt-get install -y indy-node libindy' returned a non-zero code: 100
```
@WadeBarnes  Is there some workaround to this problem, esp. because this thread is 8 months old? Thanks in advance.

**Comment by cjhowland** [comment]
@pSchlarb Could you provide a brief update on this PR? With recent branch changes and the current development process on Indy Node/Plenum, we are wondering if these changes are still viable. If so, please close this PR and retarget it to `main`.

We will discuss and determine which PRs should be merged or closed at the next Indy Contributors Working Group meeting on May 9, 2023.

**Comment by pSchlarb** [comment]
I think I will encounter this issue during the testing for the new network from scratch documentation. And if persistent will fix it with that PR,if that is ok. Or should it be 2 separate prs @WadeBarnes?

**Comment by WadeBarnes** [comment]
@pSchlarb, One PR would be fine.  I'd close this PR.

**Pull request closed without merging**
