### PR TITLE
Upgrade GHA versions

### PR DESCRIPTION
**Pull request by WadeBarnes**
- Address warning raised while running workflows.

### CODE REVIEW

**Comment by WadeBarnes** [comment]
Build issues encountered here require the pending changes to `hyperledger/indy-shared-gha` to be integrated; https://github.com/hyperledger/indy-shared-gha/pull/28

**Review by ryjones — APPROVED** [review]

**Comment by WadeBarnes** [comment]
Required changes in `hyperledger/indy-shared-gha` have been merged, tagged, and released.  Builds for this PR have been restarted.

**Comment by WadeBarnes** [comment]
Missed updating some actions.  Please hold off merging.  I'll add the missing upgrades.

**Comment by WadeBarnes** [comment]
Ready to go

**Review by ryjones — APPROVED** [review]

**Review by swcurran — APPROVED** [review]

**Pull request merged**
